import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import ServiceDropdown from "@/components/ServiceDropdown";
import SideBar from "@/components/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="reative">
          <div className="sticky top-0 w-full z-[40]">
            <NavBar />
          </div>
          <SideBar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
